name: diagnostics (coursera-wacz-home)
on:
  pull_request:
    paths:
      - materials/coursera-wacz-home/**
      - .github/workflows/tests-coursera-wacz-home.yml
      - .github/workflows/clone-diagnostics.yml
  push:
    paths:
      - materials/coursera-wacz-home/**
      - .github/workflows/tests-coursera-wacz-home.yml
      - .github/workflows/clone-diagnostics.yml
permissions:
  contents: read
concurrency:
  group: diagnostics-coursera-wacz-home-${{ github.ref }}
  cancel-in-progress: true
jobs:
  diagnostics:
    uses: ./.github/workflows/clone-diagnostics.yml
    with:
      site: coursera-wacz-home
