name: diagnostics (crunchyroll)
on:
  pull_request:
    paths:
      - materials/crunchyroll/**
      - .github/workflows/tests-crunchyroll.yml
      - .github/workflows/clone-diagnostics.yml
  push:
    paths:
      - materials/crunchyroll/**
      - .github/workflows/tests-crunchyroll.yml
      - .github/workflows/clone-diagnostics.yml
permissions:
  contents: read
concurrency:
  group: diagnostics-crunchyroll-${{ github.ref }}
  cancel-in-progress: true
jobs:
  diagnostics:
    uses: ./.github/workflows/clone-diagnostics.yml
    with:
      site: crunchyroll
