name: diagnostics (craigslist)
on:
  pull_request:
    paths:
      - materials/craigslist/**
      - .github/workflows/tests-craigslist.yml
      - .github/workflows/clone-diagnostics.yml
  push:
    paths:
      - materials/craigslist/**
      - .github/workflows/tests-craigslist.yml
      - .github/workflows/clone-diagnostics.yml
permissions:
  contents: read
concurrency:
  group: diagnostics-craigslist-${{ github.ref }}
  cancel-in-progress: true
jobs:
  diagnostics:
    uses: ./.github/workflows/clone-diagnostics.yml
    with:
      site: craigslist
